
CREATE        PROCEDURE [kcsd].[p_kc_customer_phonelist] @wk_case_no varchar(10)
AS

select A.MenuCode,A.ParentCode,A.kc_rela_desc,A.kc_rela_code,A.kc_case_no,A.kc_cust_name,A.kc_target_name,A.MenuName,A.number,A.Memo,A.id,A.birthdate,A.zip,A.addr,A.addr_nr,A.papaname,A.mamaname,A.matename,A.compname,A.custstat,A.addrstat,(select kc_pusher_code from kcsd.kc_pushassign where kc_stop_date is null and kc_case_no  = @wk_case_no ) kc_pusher_code
from
(select '110' as MenuCode,null as ParentCode,c.kc_case_no,'本-'+kc_cust_nameu as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,'' as number,CASE WHEN kc_birth_date IS NULL THEN '' WHEN DATEDIFF(DAY,DATEADD(YEAR,20,kc_birth_date),kc_finsu_date) < 0 THEN '未滿20' ELSE '' END as Memo ,kc_id_no as id,kc_birth_date as birthdate,null as zip,null as addr,null as addr_nr,kc_papa_nameu as papaname,kc_mama_nameu as mamaname,kc_mate_nameu as matename,null as compname,kc_cust_stat as custstat,null as addrstat from kcsd.kc_customerloan c left join kcsd.kc_customerloan1 c1 on c1.kc_case_no = c.kc_case_no where c.kc_case_no = @wk_case_no
union
select '110001' as MenuCode,'110' as ParentCode,kc_case_no,'行動1' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,kc_mobil_no as number,kc_mobil_no_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '110002' as MenuCode,'110' as ParentCode,kc_case_no,'行動2' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,kc_fax_phone as number,kc_fax_phone_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '110003' as MenuCode,'110' as ParentCode,kc_case_no,'戶籍' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,kc_perm_phone as number,kc_perm_phone_nt as Memo ,null as id,null as birthdate,kc_perm_zip as zip,kc_perm_addr as addr,kc_perm_addr_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_perm_stat as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '110004' as MenuCode,'110' as ParentCode,kc_case_no,'住家' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,kc_curr_phone as number,kc_curr_phone_nt as Memo ,null as id,null as birthdate,kc_curr_zip as zip,kc_curr_addr as addr,kc_curr_addr_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_curr_stat as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '110005' as MenuCode,'110' as ParentCode,kc_case_no,'公司' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,kc_comp_phone as number,kc_comp_phone_nt as Memo ,null as id,null as birthdate,kc_comp_zip as zip,kc_comp_addr as addr,kc_comp_addr_nt as addr_nr,null as papaname,null as mamaname,null as matename,kc_comp_namea as compname,null as custstat,kc_comp_stat as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '110006' as MenuCode,'110' as ParentCode,kc_case_no,'帳單' as MenuName,'本' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_nameu as kc_target_name,null as kc_rela_code,null as number,null as Memo ,null as id,null as birthdate,kc_zip_code as zip,kc_bill_addr as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '120' as MenuCode,null as ParentCode,c.kc_case_no,'保1-'+isnull(kc_cust_name1u,'無') as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,kc_rela_code1 as kc_rela_code,'' as number,CASE WHEN kc_birth_date IS NULL THEN '' WHEN DATEDIFF(DAY,DATEADD(YEAR,20,kc_birth_date1),kc_finsu_date) < 0 THEN '未滿20' ELSE '' END as Memo ,kc_id_no1 as id,kc_birth_date1 as birthdate,null as zip,null as addr,null as addr_nr,kc_papa_name1u as papaname,kc_mama_name1u as mamaname,kc_mate_name1u as matename,null as compname,kc_cust_stat1 as custstat,null as addrstat from kcsd.kc_customerloan c left join kcsd.kc_customerloan1 c1 on c1.kc_case_no = c.kc_case_no where c.kc_case_no = @wk_case_no
union
select '120001' as MenuCode,'120' as ParentCode,kc_case_no,'行動1' as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,null as kc_rela_code,kc_mobil_no1 as number,kc_mobil_no1_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '120002' as MenuCode,'120' as ParentCode,kc_case_no,'行動2' as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,null as kc_rela_code,kc_mobil_no12 as number,kc_mobil_no12_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '120003' as MenuCode,'120' as ParentCode,kc_case_no,'戶籍' as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,null as kc_rela_code,kc_perm_phone1 as  number,kc_perm_phone1_nt as Memo ,null as id,null as birthdate,kc_perm_zip1 as zip,kc_perm_addr1 as addr,kc_perm_addr1_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_perm_stat1 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '120004' as MenuCode,'120' as ParentCode,kc_case_no,'住家' as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,null as kc_rela_code,kc_curr_phone1 as number,kc_curr_phone1_nt as Memo ,null as id,null as birthdate,kc_curr_zip1 as zip,kc_curr_addr1 as addr,kc_curr_addr1_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_curr_stat1 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '120005' as MenuCode,'120' as ParentCode,kc_case_no,'公司' as MenuName,'保1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name1u as kc_target_name,null as kc_rela_code,kc_comp_phone1 as number,kc_comp_phone1_nt as Memo ,null as id,null as birthdate,kc_comp_zip1 as zip,kc_comp_addr1 as addr,kc_comp_addr1_nt as addr_nr,null as papaname,null as mamaname,null as matename,kc_comp_namea1 as compname,null as custstat,kc_comp_stat1 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '130' as MenuCode,null as ParentCode,c.kc_case_no,'保2-'+isnull(kc_cust_name2u,'無') as MenuName,'保2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name2u as kc_target_name,kc_rela_code2 as kc_rela_code,'' as number,CASE WHEN kc_birth_date IS NULL THEN '' WHEN DATEDIFF(DAY,DATEADD(YEAR,20,kc_birth_date2),kc_finsu_date) < 0 THEN '未滿20' ELSE '' END as Memo ,kc_id_no2 as id,kc_birth_date2 as birthdate,null as zip,null as addr,null as addr_nr,kc_papa_name2u as papaname,kc_mama_name2u as mamaname,kc_mate_name2u as matename,null as compname,kc_cust_stat2 as custstat,null as addrstat from kcsd.kc_customerloan c left join kcsd.kc_customerloan1 c1 on c1.kc_case_no = c.kc_case_no where c.kc_case_no = @wk_case_no
union
select '130001' as MenuCode,'130' as ParentCode,kc_case_no,'行動1' as MenuName,'保2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name2u as kc_target_name,null as kc_rela_code,kc_mobil_no2 as number,kc_mobil_no2_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '130002' as MenuCode,'130' as ParentCode,kc_case_no,'戶籍' as MenuName,'保2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name2u as kc_target_name,null as kc_rela_code,kc_perm_phone2 as  number,kc_perm_phone2_nt as Memo ,null as id,null as birthdate,kc_perm_zip2 as zip,kc_perm_addr2 as addr,kc_perm_addr2_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_perm_stat2 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '130003' as MenuCode,'130' as ParentCode,kc_case_no,'住家' as MenuName,'保2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name2u as kc_target_name,null as kc_rela_code,kc_curr_phone2 as number,kc_curr_phone2_nt as Memo ,null as id,null as birthdate,kc_curr_zip2 as zip,kc_curr_addr2 as addr,kc_curr_addr2_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,kc_curr_stat2 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '130004' as MenuCode,'130' as ParentCode,kc_case_no,'公司' as MenuName,'保2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name2u as kc_target_name,null as kc_rela_code,kc_comp_phone2 as number,kc_comp_phone2_nt as Memo ,null as id,null as birthdate,kc_comp_zip2 as zip,kc_comp_addr2 as addr,kc_comp_addr2_nt as addr_nr,null as papaname,null as mamaname,null as matename,kc_comp_namea2 as compname,null as custstat,kc_comp_stat2 as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '140' as MenuCode,null as ParentCode,kc_case_no,'聯1-'+isnull(kc_cust_name3u,'無') as MenuName,'聯1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name3u as kc_target_name,kc_rela_code3 as kc_rela_code,'' as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '140001' as MenuCode,'140' as ParentCode,kc_case_no,'行動1' as MenuName,'聯1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name3u as kc_target_name,null as kc_rela_code,kc_mobil_no3 as number,kc_mobil_no3_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '140002' as MenuCode,'140' as ParentCode,kc_case_no,'住家' as MenuName,'聯1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name3u as kc_target_name,null as kc_rela_code,kc_curr_phone3 as number,kc_curr_phone3_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '140003' as MenuCode,'140' as ParentCode,kc_case_no,'公司' as MenuName,'聯1' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name3u as kc_target_name,null as kc_rela_code,kc_comp_phone3 as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '150' as MenuCode,null as ParentCode,kc_case_no,'聯2-'+isnull(kc_cust_name4u,'無') as MenuName,'聯2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name4u as kc_target_name,kc_rela_code4 as kc_rela_code,'' as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '150001' as MenuCode,'150' as ParentCode,kc_case_no,'行動1' as MenuName,'聯2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name4u as kc_target_name,null as kc_rela_code,kc_mobil_no4 as number,kc_mobil_no4_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '150002' as MenuCode,'150' as ParentCode,kc_case_no,'住家' as MenuName,'聯2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name4u as kc_target_name,null as kc_rela_code,kc_curr_phone4 as number,kc_curr_phone4_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '150003' as MenuCode,'150' as ParentCode,kc_case_no,'公司' as MenuName,'聯2' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name4u as kc_target_name,null as kc_rela_code,kc_comp_phone4 as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '160' as MenuCode,null as ParentCode,kc_case_no,'聯3-'+isnull(kc_cust_name6u,'無') as MenuName,'聯3' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name6u as kc_target_name,kc_rela_code6 as kc_rela_code,'' as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '160001' as MenuCode,'160' as ParentCode,kc_case_no,'行動1' as MenuName,'聯3' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name6u as kc_target_name,null as kc_rela_code,kc_mobil_no6 as number,kc_mobil_no6_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '160002' as MenuCode,'160' as ParentCode,kc_case_no,'住家' as MenuName,'聯3' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name6u as kc_target_name,null as kc_rela_code,kc_curr_phone6 as number,kc_curr_phone6_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '160003' as MenuCode,'160' as ParentCode,kc_case_no,'公司' as MenuName,'聯3' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_cust_name6u as kc_target_name,null as kc_rela_code,kc_comp_phone6 as number,null as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan where kc_case_no = @wk_case_no
union
select '170' as MenuCode,null as ParentCode,kc_customerloan.kc_case_no,'使-'+isnull(kc_customerloan1.kc_cust_name5u,'無') as MenuName,'使' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_customerloan1.kc_cust_name5u as kc_target_name,kc_customerloan1.kc_rela_code5 as kc_rela_code,'' as number,null as Memo ,kc_customerloan1.kc_id_no5 as id,kc_customerloan1.kc_birth_date5 as birthdate,null as zip,null as addr,null as addr_nr,kc_customerloan1.kc_papa_name5u as papaname,kc_customerloan1.kc_mama_name5u as mamaname,kc_customerloan1.kc_mate_name5u as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan1 inner join kcsd.kc_customerloan on kc_customerloan.kc_case_no = kc_customerloan1.kc_case_no where kc_customerloan.kc_case_no = @wk_case_no
union
select '170001' as MenuCode,'170' as ParentCode,kc_customerloan.kc_case_no,'行動1' as MenuName,'使' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_customerloan1.kc_cust_name5u as kc_target_name,null as kc_rela_code,kc_customerloan1.kc_mobil_no5 as number, kc_customerloan1.kc_mobil_no5_nt as Memo ,null as id,null as birthdate,null as zip,null as addr,null as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan1 inner join kcsd.kc_customerloan on kc_customerloan.kc_case_no = kc_customerloan1.kc_case_no where kc_customerloan.kc_case_no = @wk_case_no
union
select '170002' as MenuCode,'170' as ParentCode,kc_customerloan.kc_case_no,'戶籍' as MenuName,'使' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_customerloan1.kc_cust_name5u as kc_target_name,null as kc_rela_code,kc_customerloan1.kc_perm_phone5 as number,kc_customerloan1.kc_perm_phone5_nt as Memo ,null as id,null as birthdate,kc_customerloan1.kc_perm_zip5 as zip,kc_customerloan1.kc_perm_addr5 as addr,kc_customerloan1.kc_perm_addr5_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan1 inner join kcsd.kc_customerloan on kc_customerloan.kc_case_no = kc_customerloan1.kc_case_no where kc_customerloan.kc_case_no = @wk_case_no
union
select '170003' as MenuCode,'170' as ParentCode,kc_customerloan.kc_case_no,'住家' as MenuName,'使' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_customerloan1.kc_cust_name5u as kc_target_name,null as kc_rela_code,kc_customerloan1.kc_curr_phone5 as number, kc_customerloan1.kc_curr_phone5_nt as Memo ,null as id,null as birthdate,kc_customerloan1.kc_curr_zip5 as zip,kc_customerloan1.kc_curr_addr5 as addr,kc_customerloan1.kc_curr_addr5_nt as addr_nr,null as papaname,null as mamaname,null as matename,null as compname,null as custstat,null as addrstat from kcsd.kc_customerloan1 inner join kcsd.kc_customerloan on kc_customerloan.kc_case_no = kc_customerloan1.kc_case_no where kc_customerloan.kc_case_no = @wk_case_no
union
select '170004' as MenuCode,'170' as ParentCode,kc_customerloan.kc_case_no,'公司' as MenuName,'使' as kc_rela_desc,kc_cust_nameu as kc_cust_name,kc_customerloan1.kc_cust_name5u as kc_target_name,null as kc_rela_code,kc_customerloan1.kc_comp_phone5 as number, kc_customerloan1.kc_comp_phone5_nt as Memo ,null as id,null as birthdate,kc_customerloan1.kc_comp_zip5 as zip,kc_customerloan1.kc_comp_addr5 as addr,kc_customerloan1.kc_comp_addr5_nt as addr_nr,null as papaname,null as mamaname,null as matename,kc_customerloan1.kc_comp_namea5 as compname,null as custstat,null as addrstat from kcsd.kc_customerloan1 inner join kcsd.kc_customerloan on kc_customerloan.kc_case_no = kc_customerloan1.kc_case_no where kc_customerloan.kc_case_no = @wk_case_no
) as A
where (A.number IS NOT NULL or A.addr IS NOT NULL)
