CREATE TABLE [kcsd].[kc_cpdata] (
    [kc_cp_no]               VARCHAR (10)   NOT NULL,
    [kc_cp_date]             SMALLDATETIME  NULL,
    [kc_emp_code]            VARCHAR (6)    NULL,
    [kc_area_code]           VARCHAR (2)    NULL,
    [kc_cp_user]             VARCHAR (20)   NULL,
    [kc_cust_name]           VARCHAR (60)   NOT NULL,
    [kc_cust_nameu]          NVARCHAR (60)  NULL,
    [kc_id_no]               VARCHAR (10)   NOT NULL,
    [kc_id_err]              VARCHAR (1)    NULL,
    [kc_papa_nameu]          NVARCHAR (60)  NULL,
    [kc_mama_nameu]          NVARCHAR (60)  NULL,
    [kc_mate_nameu]          NVARCHAR (60)  NULL,
    [kc_cust_name1u]         NVARCHAR (60)  NULL,
    [kc_id_no1]              VARCHAR (10)   NULL,
    [kc_id_err1]             VARCHAR (1)    NULL,
    [kc_papa_name1u]         NVARCHAR (60)  NULL,
    [kc_mama_name1u]         NVARCHAR (60)  NULL,
    [kc_mate_name1u]         NVARCHAR (60)  NULL,
    [kc_cust_name2u]         NVARCHAR (60)  NULL,
    [kc_id_no2]              VARCHAR (10)   NULL,
    [kc_id_err2]             VARCHAR (1)    NULL,
    [kc_papa_name2u]         NVARCHAR (60)  NULL,
    [kc_mama_name2u]         NVARCHAR (60)  NULL,
    [kc_mate_name2u]         NVARCHAR (60)  NULL,
    [kc_cp_memo]             VARCHAR (150)  NULL,
    [kc_apply_stat]          VARCHAR (2)    NULL,
    [kc_appv_user]           VARCHAR (20)   NULL,
    [kc_appv_date]           SMALLDATETIME  NULL,
    [kc_rej_note]            VARCHAR (150)  NULL,
    [kc_agent_code]          VARCHAR (30)   NULL,
    [kc_prod_type]           VARCHAR (2)    NULL,
    [kc_loan_type]           VARCHAR (3)    NULL,
    [kc_intr_fee]            INT            NULL,
    [kc_intr_reason]         VARCHAR (2)    NULL,
    [kc_insu_year]           VARCHAR (2)    NULL,
    [kc_loan_perd]           TINYINT        NULL,
    [kc_perd_fee]            INT            NULL,
    [kc_cash_price]          INT            NULL,
    [kc_strt_fee]            INT            NULL,
    [kc_give_amt]            INT            NULL,
    [kc_new_flag]            VARCHAR (1)    NULL,
    [kc_lock_amt]            TINYINT        NULL,
    [kc_issu_code]           VARCHAR (6)    NULL,
    [kc_brok_fee]            INT            NULL,
    [kc_all_cost]            INT            NULL,
    [kc_gros_rate]           REAL           NULL,
    [kc_cons_rate]           REAL           NULL,
    [kc_licn_no]             VARCHAR (10)   NULL,
    [kc_movable_flag]        VARCHAR (4)    NULL,
    [kc_drive_flag]          VARCHAR (4)    NULL,
    [kc_cred_stat]           VARCHAR (1)    NULL,
    [kc_cred_stat1]          VARCHAR (1)    NULL,
    [kc_cred_stat2]          VARCHAR (1)    NULL,
    [kc_want_flag]           VARCHAR (4)    NULL,
    [kc_want_flag1]          VARCHAR (4)    NULL,
    [kc_want_flag2]          VARCHAR (4)    NULL,
    [kc_debt_flag]           VARCHAR (4)    NULL,
    [kc_debt_flag1]          VARCHAR (4)    NULL,
    [kc_debt_flag2]          VARCHAR (4)    NULL,
    [kc_lawc_flag]           VARCHAR (4)    NULL,
    [kc_lawc_flag1]          VARCHAR (4)    NULL,
    [kc_lawc_flag2]          VARCHAR (4)    NULL,
    [kc_black_flag]          VARCHAR (4)    NULL,
    [kc_black_flag1]         VARCHAR (4)    NULL,
    [kc_black_flag2]         VARCHAR (4)    NULL,
    [kc_decline_flag]        VARCHAR (4)    NULL,
    [kc_decline_flag1]       VARCHAR (4)    NULL,
    [kc_decline_flag2]       VARCHAR (4)    NULL,
    [kc_crdt_user]           VARCHAR (20)   NULL,
    [kc_crdt_date]           SMALLDATETIME  NULL,
    [kc_updt_user]           VARCHAR (20)   NULL,
    [kc_updt_date]           SMALLDATETIME  NULL,
    [kc_insu_amt]            INT            NULL,
    [kc_insu_amt1]           INT            NULL,
    [kc_insu_amt2]           INT            NULL,
    [kc_car_cc]              SMALLINT       NULL,
    [kc_proc_fee]            INT            NULL,
    [kc_collarcar_fee]       INT            NULL,
    [kc_birth_date]          DATETIME       NULL,
    [kc_birth_date1]         DATETIME       NULL,
    [kc_birth_date2]         DATETIME       NULL,
    [kc_labor_flag]          VARCHAR (1)    NULL,
    [kc_labor_flag1]         VARCHAR (1)    NULL,
    [kc_labor_flag2]         VARCHAR (1)    NULL,
    [kc_ccis_flag]           VARCHAR (1)    NULL,
    [kc_ccis_flag1]          VARCHAR (1)    NULL,
    [kc_ccis_flag2]          VARCHAR (1)    NULL,
    [kc_ticket_fee]          INT            NULL,
    [kc_ticket_fee1]         INT            NULL,
    [kc_ticket_fee2]         INT            NULL,
    [kc_jcic_flag]           VARCHAR (1)    NULL,
    [kc_jcic_flag1]          VARCHAR (1)    NULL,
    [kc_jcic_flag2]          VARCHAR (1)    NULL,
    [kc_movablep_flag]       VARCHAR (1)    NULL,
    [kc_movablep_flag1]      VARCHAR (1)    NULL,
    [kc_movablep_flag2]      VARCHAR (1)    NULL,
    [kc_sales_memo]          VARCHAR (150)  NULL,
    [kc_comp_code]           VARCHAR (4)    NULL,
    [kc_workover_flag]       VARCHAR (1)    NULL,
    [kc_sales_code]          VARCHAR (6)    NULL,
    [kc_car_brand]           VARCHAR (2)    NULL,
    [kc_car_model]           NVARCHAR (60)  NULL,
    [kc_mfd_year]            VARCHAR (4)    NULL,
    [kc_eng_no]              VARCHAR (20)   NULL,
    [kc_pcase_no]            VARCHAR (10)   NULL,
    [kc_add_fee]             INT            NULL,
    [kc_perm_addr]           VARCHAR (100)  NULL,
    [kc_perm_addr1]          VARCHAR (100)  NULL,
    [kc_perm_addr2]          VARCHAR (100)  NULL,
    [kc_issue_date]          NVARCHAR (100) NULL,
    [kc_issue_date1]         VARCHAR (100)  NULL,
    [kc_issue_date2]         VARCHAR (100)  NULL,
    [kc_partner_no]          VARCHAR (10)   NULL,
    [kc_dom_flag]            VARCHAR (1)    NULL,
    [kc_dom_flag1]           VARCHAR (1)    NULL,
    [kc_dom_flag2]           VARCHAR (1)    NULL,
    [kc_branch_code]         VARCHAR (4)    NULL,
    [kc_dealer_data]         NVARCHAR (500) NULL,
    [kc_dealer_memo]         NVARCHAR (500) NULL,
    [kc_further_flag]        VARCHAR (1)    NULL,
    [kc_further_user]        VARCHAR (20)   NULL,
    [kc_further_date]        SMALLDATETIME  NULL,
    [kc_model_code]          VARCHAR (4)    NULL,
    [kc_further_flag1]       VARCHAR (1)    NULL,
    [kc_further_user1]       VARCHAR (20)   NULL,
    [kc_further_date1]       SMALLDATETIME  NULL,
    [kc_further_flag2]       VARCHAR (1)    NULL,
    [kc_further_user2]       VARCHAR (20)   NULL,
    [kc_further_date2]       SMALLDATETIME  NULL,
    [kc_further_flag3]       VARCHAR (1)    NULL,
    [kc_further_user3]       VARCHAR (20)   NULL,
    [kc_further_date3]       SMALLDATETIME  NULL,
    [kc_further_flag4]       VARCHAR (1)    NULL,
    [kc_further_user4]       VARCHAR (20)   NULL,
    [kc_further_date4]       SMALLDATETIME  NULL,
    [kc_further_flag5]       VARCHAR (1)    NULL,
    [kc_further_user5]       VARCHAR (20)   NULL,
    [kc_further_date5]       SMALLDATETIME  NULL,
    [kc_cardstatus_type]     VARCHAR (2)    NULL,
    [kc_carduse_type]        VARCHAR (2)    NULL,
    [kc_issuing_type]        VARCHAR (2)    NULL,
    [kc_source_type]         VARCHAR (2)    NULL,
    [kc_data_chk1]           VARCHAR (1)    NULL,
    [kc_data_chk2]           VARCHAR (1)    NULL,
    [kc_data_chk3]           VARCHAR (1)    NULL,
    [kc_risk_score]          INT            NULL,
    [kc_mobil_no]            VARCHAR (11)   NULL,
    [kc_contact_memo]        VARCHAR (100)  NULL,
    [kc_perm_addr3]          VARCHAR (100)  NULL,
    [kc_perm_phone]          VARCHAR (13)   NULL,
    [kc_permmember_type]     VARCHAR (10)   NULL,
    [kc_permtime_type]       VARCHAR (2)    NULL,
    [kc_permreside_type]     VARCHAR (2)    NULL,
    [kc_curr_addr]           VARCHAR (100)  NULL,
    [kc_curr_phone]          VARCHAR (11)   NULL,
    [kc_currmember_type]     VARCHAR (10)   NULL,
    [kc_currtime_type]       VARCHAR (2)    NULL,
    [kc_currreside_type]     VARCHAR (2)    NULL,
    [kc_marry_type]          VARCHAR (2)    NULL,
    [kc_child_cnt]           INT            NULL,
    [kc_edu_type]            VARCHAR (2)    NULL,
    [kc_insurance_type]      VARCHAR (2)    NULL,
    [kc_comp_addr]           VARCHAR (100)  NULL,
    [kc_comp_phone]          VARCHAR (11)   NULL,
    [kc_comp_desc]           VARCHAR (40)   NULL,
    [kc_job_type]            VARCHAR (2)    NULL,
    [kc_jobtitle_type]       VARCHAR (2)    NULL,
    [kc_income_cnt]          INT            NULL,
    [kc_workyear_cnt]        INT            NULL,
    [kc_workmonth_cnt]       INT            NULL,
    [kc_moneybank_type]      VARCHAR (10)   NULL,
    [kc_secret_type3]        VARCHAR (2)    NULL,
    [kc_cust_name3u]         VARCHAR (20)   NULL,
    [kc_cust_name4u]         VARCHAR (20)   NULL,
    [kc_lowsource_type]      VARCHAR (2)    NULL,
    [kc_lowsource_memo]      VARCHAR (20)   NULL,
    [kc_line_no]             VARCHAR (20)   NULL,
    [kc_FB_no]               VARCHAR (20)   NULL,
    [kc_IG_no]               VARCHAR (20)   NULL,
    [kc_email_no]            VARCHAR (50)   NULL,
    [kc_staging_desc]        VARCHAR (10)   NULL,
    [kc_staging_type]        VARCHAR (100)  NULL,
    [kc_perm_type]           VARCHAR (2)    NULL,
    [kc_payment_type]        VARCHAR (2)    NULL,
    [kc_payment_stat]        VARCHAR (100)  NULL,
    [kc_useful_cnt]          INT            NULL,
    [kc_mobil_no4]           VARCHAR (11)   NULL,
    [kc_mobil_no3]           VARCHAR (11)   NULL,
    [kc_cfm_stat]            VARCHAR (2)    NULL,
    [kc_cfm_user]            VARCHAR (20)   NULL,
    [kc_cfm_date]            SMALLDATETIME  NULL,
    [kc_bankbook_name]       NVARCHAR (60)  NULL,
    [kc_bankbook_account]    VARCHAR (20)   NULL,
    [kc_boboQRcode_date]     SMALLDATETIME  NULL,
    [kc_secret_type4]        VARCHAR (2)    NULL,
    [kc_relation_no3]        VARCHAR (10)   NULL,
    [kc_relation_no4]        VARCHAR (10)   NULL,
    [kc_card_no]             VARCHAR (20)   NULL,
    [kc_card_stat]           VARCHAR (20)   NULL,
    [kc_mobil_no1]           VARCHAR (11)   NULL,
    [kc_contact_memo1]       VARCHAR (100)  NULL,
    [kc_relation_no1]        VARCHAR (10)   NULL,
    [kc_line_no1]            VARCHAR (20)   NULL,
    [kc_FB_no1]              VARCHAR (20)   NULL,
    [kc_perm_phone1]         VARCHAR (11)   NULL,
    [kc_permmember_type1]    VARCHAR (10)   NULL,
    [kc_permtime_type1]      VARCHAR (2)    NULL,
    [kc_permreside_type1]    VARCHAR (2)    NULL,
    [kc_curr_addr1]          VARCHAR (100)  NULL,
    [kc_curr_phone1]         VARCHAR (11)   NULL,
    [kc_currmember_type1]    VARCHAR (10)   NULL,
    [kc_currtime_type1]      VARCHAR (2)    NULL,
    [kc_currreside_type1]    VARCHAR (2)    NULL,
    [kc_comp_desc1]          VARCHAR (100)  NULL,
    [kc_comp_addr1]          VARCHAR (100)  NULL,
    [kc_comp_phone1]         VARCHAR (11)   NULL,
    [kc_comp_ext1]           VARCHAR (10)   NULL,
    [kc_lowsource_memo1]     VARCHAR (100)  NULL,
    [kc_lowsource_type1]     VARCHAR (2)    NULL,
    [kc_comp_ext]            VARCHAR (10)   NULL,
    [kc_income_cnt1]         INT            NULL,
    [kc_workyear_cnt1]       INT            NULL,
    [kc_workmonth_cnt1]      INT            NULL,
    [kc_jobtitle_type1]      VARCHAR (2)    NULL,
    [kc_job_type1]           VARCHAR (2)    NULL,
    [kc_moneybank_type1]     VARCHAR (2)    NULL,
    [kc_brand_code]          VARCHAR (2)    NULL,
    [kc_apply_memo]          VARCHAR (100)  NULL,
    [kc_further_flag6]       VARCHAR (1)    NULL,
    [kc_further_user6]       VARCHAR (20)   NULL,
    [kc_further_date6]       SMALLDATETIME  NULL,
    [kc_further_flag7]       VARCHAR (1)    NULL,
    [kc_further_user7]       VARCHAR (20)   NULL,
    [kc_further_date7]       SMALLDATETIME  NULL,
    [kc_videocc_type]        VARCHAR (1)    NULL,
    [PrintMark]              VARCHAR (1)    NULL,
    [CarrierType]            VARCHAR (6)    NULL,
    [CarrierId1]             VARCHAR (64)   NULL,
    [kc_draft_addr]          VARCHAR (100)  NULL,
    [kc_Rchk_flag]           VARCHAR (1)    NULL,
    [kc_crdt_date1]          SMALLDATETIME  NULL,
    [kc_crdt_date2]          SMALLDATETIME  NULL,
    [kc_dect_amt]            INT            NULL,
    [kc_pay_target]          VARCHAR (2)    NULL,
    [kc_invo_caseno]         VARCHAR (10)   NULL,
    [kc_rate_type]           VARCHAR (2)    NULL,
    [kc_id2_no]              VARCHAR (10)   NULL,
    [kc_id2_no1]             VARCHAR (10)   NULL,
    [kc_id2_no2]             VARCHAR (10)   NULL,
    [kc_lawdeal_stat]        VARCHAR (2)    NULL,
    [kc_laws_memo]           VARCHAR (100)  NULL,
    [kc_healthID_no]         VARCHAR (12)   NULL,
    [kc_healthID_no1]        VARCHAR (12)   NULL,
    [kc_healthID_no2]        VARCHAR (12)   NULL,
    [kc_delivery_date]       SMALLDATETIME  NULL,
    [kc_delivery_user]       VARCHAR (10)   NULL,
    [kc_cust_name6u]         VARCHAR (20)   NULL,
    [kc_mobil_no6]           VARCHAR (13)   NULL,
    [kc_secret_type6]        VARCHAR (2)    NULL,
    [kc_relation_no6]        VARCHAR (10)   NULL,
    [kc_MSapply_date]        SMALLDATETIME  NULL,
    [kc_MSapply_user]        VARCHAR (10)   NULL,
    [kc_MS_memo]             VARCHAR (100)  NULL,
    [kc_ID0K_type]           VARCHAR (2)    NULL,
    [kc_citizenship_type]    VARCHAR (6)    NULL,
    [kc_similarity_per]      VARCHAR (3)    NULL,
    [kc_liveness_a]          VARCHAR (3)    NULL,
    [kc_liveness_b]          VARCHAR (3)    NULL,
    [kc_similarity_per1]     VARCHAR (3)    NULL,
    [kc_liveness_a1]         VARCHAR (3)    NULL,
    [kc_liveness_b1]         VARCHAR (3)    NULL,
    [kc_twca_flag]           VARCHAR (1)    NULL,
    [kc_twca_flag1]          VARCHAR (1)    NULL,
    [kc_proc_per]            VARCHAR (10)   NULL,
    [kc_proc_type]           VARCHAR (2)    NULL,
    [kc_apply_fee]           INT            NULL,
    [kc_midclause_flag]      VARCHAR (1)    NULL,
    [kc_midclause_date]      DATETIME       NULL,
    [kc_midclause_flag1]     VARCHAR (1)    NULL,
    [kc_midclause_date1]     DATETIME       NULL,
    [kc_agency_phone]        VARCHAR (13)   NULL,
    [kc_order_no]            VARCHAR (30)   NULL,
    [kc_finish_flag]         VARCHAR (1)    NULL,
    [kc_work_state]          VARCHAR (1)    NULL,
    [kc_credit_state]        VARCHAR (1)    NULL,
    [kc_credit_amount]       VARCHAR (50)   NULL,
    [kc_refund_bank_no]      VARCHAR (10)   NULL,
    [kc_credit_bank]         VARCHAR (50)   NULL,
    [kc_refund_bank_name]    VARCHAR (50)   NULL,
    [kc_refund_bank_acc]     VARCHAR (20)   NULL,
    [kc_loc_quota]           INT            NULL,
    [kc_loc_remaining]       INT            NULL,
    [kc_member_no]           VARCHAR (30)   NULL,
    [kc_introduce_code]      VARCHAR (11)   NULL,
    [kc_membertarget_type]   VARCHAR (2)    NULL,
    [kc_dudu_type]           VARCHAR (2)    NULL,
    [CompID]                 VARCHAR (8)    NULL,
    [kc_citizenship_name]    VARCHAR (40)   NULL,
    [kc_citizenship_type1]   VARCHAR (2)    NULL,
    [kc_citizenship_name1]   VARCHAR (50)   NULL,
    [kc_citizenship_type2]   VARCHAR (2)    NULL,
    [kc_citizenship_name2]   VARCHAR (50)   NULL,
    [kc_invoice_address]     VARCHAR (100)  NULL,
    [kc_issue2_date]         VARCHAR (20)   NULL,
    [kc_expiry_date]         VARCHAR (20)   NULL,
    [kc_backid_no]           VARCHAR (20)   NULL,
    [kc_issue2_date1]        VARCHAR (20)   NULL,
    [kc_expiry_date1]        VARCHAR (20)   NULL,
    [kc_backid_no1]          VARCHAR (20)   NULL,
    [kc_issue2_date2]        VARCHAR (20)   NULL,
    [kc_expiry_date2]        VARCHAR (20)   NULL,
    [kc_backid_no2]          VARCHAR (20)   NULL,
    [kc_marketschedule_memo] VARCHAR (100)  NULL,
    CONSTRAINT [PK_kc_cpdata] PRIMARY KEY CLUSTERED ([kc_cp_no] ASC)
);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_1]
    ON [kcsd].[kc_cpdata]([kc_cust_nameu] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_10]
    ON [kcsd].[kc_cpdata]([kc_papa_name2u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_11]
    ON [kcsd].[kc_cpdata]([kc_mama_name2u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_12]
    ON [kcsd].[kc_cpdata]([kc_mate_name2u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_13]
    ON [kcsd].[kc_cpdata]([kc_area_code] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_2]
    ON [kcsd].[kc_cpdata]([kc_papa_nameu] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_3]
    ON [kcsd].[kc_cpdata]([kc_mama_nameu] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_4]
    ON [kcsd].[kc_cpdata]([kc_mate_nameu] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_5]
    ON [kcsd].[kc_cpdata]([kc_cust_name1u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_6]
    ON [kcsd].[kc_cpdata]([kc_papa_name1u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_7]
    ON [kcsd].[kc_cpdata]([kc_mama_name1u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_8]
    ON [kcsd].[kc_cpdata]([kc_mate_name1u] ASC);


GO
CREATE NONCLUSTERED INDEX [i_kc_cpdata_9]
    ON [kcsd].[kc_cpdata]([kc_cust_name2u] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'DuDu意願 (25.05.22 Ray)', @level0type = N'SCHEMA', @level0name = N'kcsd', @level1type = N'TABLE', @level1name = N'kc_cpdata', @level2type = N'COLUMN', @level2name = N'kc_dudu_type';

