CREATE TABLE [kcsd].[kc_loanpayment_log] (
    [kc_case_no]    VARCHAR (10) NOT NULL,
    [kc_item_no]    INT          NOT NULL,
    [kc_log_user]   VARCHAR (20) NOT NULL,
    [kc_log_date]   DATETIME     NOT NULL,
    [kc_reason]     VARCHAR (50) NOT NULL,
    [kc_perd_no]    SMALLINT     NOT NULL,
    [kc_expt_date]  DATETIME     NULL,
    [kc_expt_fee]   INT          NULL,
    [kc_pay_date]   DATETIME     NULL,
    [kc_pay_fee]    INT          NULL,
    [kc_rema_fee]   INT          NULL,
    [kc_pay_type]   VARCHAR (1)  NULL,
    [kc_trans_no]   VARCHAR (10) NULL,
    [kc_break_fee]  INT          NULL,
    [kc_intr_fee]   INT          NULL,
    [kc_rece_code]  VARCHAR (6)  NULL,
    [kc_oper_code]  VARCHAR (6)  NULL,
    [kc_memo]       VARCHAR (50) NULL,
    [kc_updt_user]  VARCHAR (10) NULL,
    [kc_updt_date]  DATETIME     NULL,
    [kc_proc_fee]   INT          NULL,
    [kc_area_code]  VARCHAR (2)  NULL,
    [kc_pv_amt]     INT          NULL,
    [kc_invo_amt]   INT          NULL,
    [kc_pvpay_amt]  INT          NULL,
    [kc_invo_rema]  INT          NULL,
    [kc_pv_amt2]    INT          NULL,
    [kc_invo_amt2]  INT          NULL,
    [kc_pvpay_amt2] INT          NULL,
    [kc_invo_rema2] INT          NULL,
    [kc_proc_amt2]  INT          NULL,
    [kc_proc_rema2] INT          NULL,
    [kc_oinvo_amt]  INT          NULL,
    [kc_invo_date]  DATETIME     NULL,
    [kc_invo_flag]  VARCHAR (1)  NULL,
    CONSTRAINT [PK_kc_loanpayment_log] PRIMARY KEY CLUSTERED ([kc_case_no] ASC, [kc_item_no] ASC)
);

