CREATE TABLE [kcsd].[kc_loantype] (
    [kc_loan_type]         VARCHAR (3)   NOT NULL,
    [kc_type_desc]         VARCHAR (20)  NOT NULL,
    [kc_new_flag]          VARCHAR (1)   NULL,
    [kc_loan_rate]         REAL          NULL,
    [IsEnable]             BIT           CONSTRAINT [DF_kc_loantype_IsEnable] DEFAULT ((0)) NULL,
    [DefaultInsu01]        BIT           NULL,
    [DefaultInsu02]        BIT           NULL,
    [kc_proc_fee]          INT           NULL,
    [kc_collarcar_fee]     INT           NULL,
    [kc_rate_type]         VARCHAR (2)   NULL,
    [kc_rate_type01]       VARCHAR (2)   NULL,
    [kc_rate_type02]       VARCHAR (2)   NULL,
    [kc_rate_type03]       VARCHAR (2)   NULL,
    [kc_rate_type04]       VARCHAR (2)   NULL,
    [kc_rate_type05]       VARCHAR (2)   NULL,
    [kc_rate_type06]       VARCHAR (2)   NULL,
    [kc_rate_type07]       VARCHAR (2)   NULL,
    [kc_rate_type08]       VARCHAR (2)   NULL,
    [kc_rate_type09]       VARCHAR (2)   NULL,
    [kc_rate_type10]       VARCHAR (2)   NULL,
    [kc_rate_type11]       VARCHAR (2)   NULL,
    [kc_rate_type12]       VARCHAR (2)   NULL,
    [kc_rate_type13]       VARCHAR (2)   NULL,
    [kc_rate_type14]       VARCHAR (2)   NULL,
    [kc_rate_type15]       VARCHAR (2)   NULL,
    [IsEnable_Calculation] VARCHAR (2)   NULL,
    [kc_formula]           VARCHAR (100) NULL,
    CONSTRAINT [PK__kc_loant__2B20077FDEC3FEFF] PRIMARY KEY CLUSTERED ([kc_loan_type] ASC)
);

