CREATE TABLE [kcsd].[kc_memberapptschedule] (
    [kc_member_no]         VARCHAR (20)  NOT NULL,
    [kc_appt_date]         SMALLDATETIME NOT NULL,
    [kc_item_no]           SMALLINT      NOT NULL,
    [kc_sales_code]        VARCHAR (6)   NULL,
    [kc_appt_amt]          INT           NULL,
    [kc_book_flag]         BIT           NOT NULL,
    [kc_appt_stat]         VARCHAR (1)   NULL,
    [kc_next_date]         SMALLDATETIME NULL,
    [kc_updt_user]         VARCHAR (10)  NULL,
    [kc_updt_date]         SMALLDATETIME NULL,
    [kc_pay_type]          VARCHAR (1)   NULL,
    [kc_pusher_code]       VARCHAR (6)   NULL,
    [kc_addr_type]         VARCHAR (4)   NULL,
    [kc_appt_type]         VARCHAR (4)   NULL,
    [kc_rela_name]         VARCHAR (20)  NULL,
    [kc_visit_date]        SMALLDATETIME NULL,
    [kc_visit_outc]        VARCHAR (200) NULL,
    [kc_visit_memo]        VARCHAR (200) NULL,
    [kc_pay_amt]           INT           NULL,
    [kc_pay_breakamt]      INT           NULL,
    [kc_receipt_no]        VARCHAR (10)  NULL,
    [kc_break_amt]         INT           NULL,
    [kc_remark]            VARCHAR (200) NULL,
    [kc_area_code]         VARCHAR (2)   NULL,
    [kc_apptschedule_type] VARCHAR (2)   NULL,
    [CreatePerson]         VARCHAR (20)  NULL,
    [CreateDate]           DATETIME      NULL
);

