CREATE TABLE [kcsd].[kc_movable] (
    [kc_cp_no]          VARCHAR (10)   NOT NULL,
    [kc_item_no]        INT            CONSTRAINT [DF_kc_movable_kc_item_no] DEFAULT ((1)) NOT NULL,
    [kc_cust_nameu]     NVARCHAR (50)  NOT NULL,
    [kc_id_no]          VARCHAR (12)   NOT NULL,
    [kc_movable_stat]   VARCHAR (2)    NOT NULL,
    [kc_movable_target] VARCHAR (2)    NOT NULL,
    [kc_licn_no]        VARCHAR (10)   NOT NULL,
    [kc_licn_type]      VARCHAR (2)    NOT NULL,
    [kc_mvdis]          VARCHAR (2)    NOT NULL,
    [kc_perm_addr]      NVARCHAR (100) NOT NULL,
    [kc_birth_date]     SMALLDATETIME  NOT NULL,
    [kc_mfg_date]       SMALLDATETIME  NOT NULL,
    [kc_eng_no]         VARCHAR (20)   NOT NULL,
    [kc_carbody_no]     VARCHAR (30)   NOT NULL,
    [kc_car_brand]      VARCHAR (2)    NOT NULL,
    [kc_car_model]      VARCHAR (30)   NOT NULL,
    [kc_car_cc]         VARCHAR (5)    NOT NULL,
    [kc_licn_date]      SMALLDATETIME  NOT NULL,
    [kc_movable_user]   VARCHAR (20)   NOT NULL,
    [kc_movable_date]   SMALLDATETIME  NOT NULL,
    [kc_update_user]    VARCHAR (20)   NULL,
    [kc_update_date]    SMALLDATETIME  NULL,
    [kc_app_user]       VARCHAR (20)   NULL,
    [kc_app_date]       SMALLDATETIME  NULL,
    [kc_treasurer_user] VARCHAR (20)   NULL,
    [kc_treasurer_date] SMALLDATETIME  NULL,
    [kc_cancel_user]    VARCHAR (20)   NULL,
    [kc_cancel_date]    SMALLDATETIME  NULL,
    [kc_cancel_no]      VARCHAR (20)   NULL,
    [kc_movable_memo]   NVARCHAR (50)  NULL,
    [kc_movable_money]  INT            NULL,
    [kc_movable_fee]    INT            NULL,
    [kc_updt_date]      SMALLDATETIME  NULL,
    [kc_updt_user]      VARCHAR (10)   NULL,
    [kc_keep_no]        VARCHAR (10)   NULL,
    [kc_process_type]   VARCHAR (6)    NULL,
    CONSTRAINT [PK_kc_movable] PRIMARY KEY CLUSTERED ([kc_cp_no] ASC, [kc_item_no] ASC)
);

