CREATE TABLE [kcsd].[kc_pettycash] (
    [kc_apply_no]     VARCHAR (10)  NOT NULL,
    [kc_pay_date]     DATETIME      NULL,
    [kc_acc_code]     VARCHAR (7)   NULL,
    [kc_acc_type]     VARCHAR (10)  NULL,
    [kc_acc_sum]      VARCHAR (50)  NULL,
    [kc_agent_code]   VARCHAR (4)   NULL,
    [kc_emp_code]     VARCHAR (4)   NULL,
    [kc_expense_fee]  INT           NULL,
    [kc_revenue_fee]  INT           NULL,
    [kc_area_code]    VARCHAR (2)   NULL,
    [kc_acc_memo]     VARCHAR (150) NULL,
    [kc_apply_user]   VARCHAR (20)  NULL,
    [kc_apply_date]   DATETIME      NULL,
    [kc_approve_user] VARCHAR (20)  NULL,
    [kc_approve_date] DATETIME      NULL,
    [kc_cfm1_flag]    VARCHAR (1)   NULL,
    [kc_cfm1_user]    VARCHAR (20)  NULL,
    [kc_cfm1_date]    DATETIME      NULL,
    [kc_cfm2_flag]    VARCHAR (1)   NULL,
    [kc_cfm2_user]    VARCHAR (20)  NULL,
    [kc_cfm2_date]    DATETIME      NULL,
    [kc_act_user]     VARCHAR (20)  NULL,
    [kc_act_date]     DATETIME      NULL,
    [kc_actmgt_user]  VARCHAR (20)  NULL,
    [kc_actmgt_date]  DATETIME      NULL,
    [kc_give_user]    VARCHAR (20)  NULL,
    [kc_give_date]    DATETIME      NULL,
    [kc_finish_user]  VARCHAR (20)  NULL,
    [kc_finish_date]  DATETIME      NULL,
    [CreatePerson]    VARCHAR (20)  NULL,
    [CreateDate]      DATETIME      NULL,
    [kc_updt_user]    VARCHAR (20)  NULL,
    [kc_updt_date]    DATETIME      NULL,
    [kc_give_type]    VARCHAR (2)   NULL,
    CONSTRAINT [PK_kc_pettycash] PRIMARY KEY CLUSTERED ([kc_apply_no] ASC)
);

