CREATE TABLE [kcsd].[lstmp] (
    [kc_case_no]          VARCHAR (10)  NOT NULL,
    [kc_item_no]          INT           NOT NULL,
    [kc_area_code]        VARCHAR (2)   NOT NULL,
    [kc_law_date]         DATETIME      NOT NULL,
    [kc_law_code]         VARCHAR (1)   NOT NULL,
    [kc_law_fmt]          VARCHAR (4)   NULL,
    [kc_perm_flag]        VARCHAR (1)   NULL,
    [kc_curr_flag]        VARCHAR (1)   NULL,
    [kc_comp_flag]        VARCHAR (1)   NULL,
    [kc_perm_flag1]       VARCHAR (1)   NULL,
    [kc_curr_flag1]       VARCHAR (1)   NULL,
    [kc_comp_flag1]       VARCHAR (1)   NULL,
    [kc_perm_flag2]       VARCHAR (1)   NULL,
    [kc_curr_flag2]       VARCHAR (1)   NULL,
    [kc_comp_flag2]       VARCHAR (1)   NULL,
    [kc_bill_flag]        VARCHAR (1)   NULL,
    [kc_send_flag]        VARCHAR (2)   NULL,
    [kc_doc_no]           VARCHAR (40)  NULL,
    [kc_doc_date]         DATETIME      NULL,
    [kc_doc_type]         VARCHAR (20)  NULL,
    [kc_court_code]       VARCHAR (10)  NULL,
    [kc_law_amt]          INT           NULL,
    [kc_law_amt1]         INT           NULL,
    [kc_comp_date]        DATETIME      NULL,
    [kc_claims_amt]       INT           NULL,
    [kc_value_date]       DATETIME      NULL,
    [kc_rate_fee]         REAL          NULL,
    [kc_litigation_amt]   INT           NULL,
    [kc_litigation_amt1]  INT           NULL,
    [kc_litigation_amt2]  INT           NULL,
    [kc_crdt_user]        VARCHAR (10)  NULL,
    [kc_crdt_date]        DATETIME      NULL,
    [kc_updt_user]        VARCHAR (10)  NULL,
    [kc_updt_date]        DATETIME      NULL,
    [kc_comp_user]        VARCHAR (10)  NULL,
    [kc_remind_flag]      VARCHAR (2)   NULL,
    [kc_remind_date]      DATETIME      NULL,
    [kc_remind_user]      NCHAR (10)    NULL,
    [CreatePerson]        VARCHAR (20)  NULL,
    [CreateDate]          DATETIME      NULL,
    [kc_legalperiod_user] VARCHAR (10)  NULL,
    [kc_legalperiod_stat] VARCHAR (2)   NULL,
    [kc_court_type]       VARCHAR (2)   NULL,
    [kc_remark]           VARCHAR (100) NULL
);

