CREATE TABLE [kcsd].[tmp_cu] (
    [kc_case_no]          VARCHAR (10)  NOT NULL,
    [kc_area_code]        VARCHAR (2)   NOT NULL,
    [kc_cp_no]            VARCHAR (10)  NULL,
    [kc_id_no]            VARCHAR (10)  NOT NULL,
    [kc_birth_date]       DATETIME      NULL,
    [kc_cust_name]        VARCHAR (60)  NULL,
    [kc_cust_nameu]       NVARCHAR (60) NULL,
    [kc_papa_nameu]       NVARCHAR (60) NULL,
    [kc_mama_nameu]       NVARCHAR (60) NULL,
    [kc_mate_nameu]       NVARCHAR (60) NULL,
    [kc_legal_agent]      NVARCHAR (60) NULL,
    [kc_cust_stat]        VARCHAR (1)   NULL,
    [kc_house_stat]       VARCHAR (1)   NULL,
    [kc_mobil_no]         VARCHAR (12)  NULL,
    [kc_mobil_no_nt]      VARCHAR (40)  NULL,
    [kc_fax_phone]        VARCHAR (15)  NULL,
    [kc_fax_phone_nt]     VARCHAR (40)  NULL,
    [kc_perm_zip]         VARCHAR (5)   NULL,
    [kc_perm_stat]        VARCHAR (1)   NULL,
    [kc_perm_addr]        VARCHAR (100) NULL,
    [kc_perm_addr_nt]     VARCHAR (40)  NULL,
    [kc_perm_phone]       VARCHAR (15)  NULL,
    [kc_perm_phone_nt]    VARCHAR (40)  NULL,
    [kc_curr_stat]        VARCHAR (1)   NULL,
    [kc_curr_zip]         VARCHAR (5)   NULL,
    [kc_curr_addr]        VARCHAR (100) NULL,
    [kc_curr_addr_nt]     VARCHAR (40)  NULL,
    [kc_curr_phone]       VARCHAR (15)  NULL,
    [kc_curr_phone_nt]    VARCHAR (40)  NULL,
    [kc_comp_stat]        VARCHAR (1)   NULL,
    [kc_comp_zip]         VARCHAR (5)   NULL,
    [kc_comp_addr]        VARCHAR (100) NULL,
    [kc_comp_addr_nt]     VARCHAR (40)  NULL,
    [kc_comp_phone]       VARCHAR (20)  NULL,
    [kc_comp_phone_nt]    VARCHAR (40)  NULL,
    [kc_comp_namea]       VARCHAR (60)  NULL,
    [kc_job_title]        VARCHAR (20)  NULL,
    [kc_exp_year]         TINYINT       NULL,
    [kc_exp_month]        TINYINT       NULL,
    [kc_id_no1]           VARCHAR (10)  NULL,
    [kc_birth_date1]      DATETIME      NULL,
    [kc_rela_code1]       VARCHAR (2)   NULL,
    [kc_cust_name1u]      NVARCHAR (60) NULL,
    [kc_papa_name1u]      NVARCHAR (60) NULL,
    [kc_mama_name1u]      NVARCHAR (60) NULL,
    [kc_mate_name1u]      NVARCHAR (60) NULL,
    [kc_legal_agent1]     NVARCHAR (60) NULL,
    [kc_cust_stat1]       VARCHAR (1)   NULL,
    [kc_house_stat1]      VARCHAR (1)   NULL,
    [kc_mobil_no1]        VARCHAR (12)  NULL,
    [kc_mobil_no1_nt]     VARCHAR (40)  NULL,
    [kc_mobil_no12]       VARCHAR (12)  NULL,
    [kc_mobil_no12_nt]    VARCHAR (40)  NULL,
    [kc_perm_stat1]       VARCHAR (1)   NULL,
    [kc_perm_zip1]        VARCHAR (5)   NULL,
    [kc_perm_addr1]       VARCHAR (100) NULL,
    [kc_perm_addr1_nt]    VARCHAR (40)  NULL,
    [kc_perm_phone1]      VARCHAR (15)  NULL,
    [kc_perm_phone1_nt]   VARCHAR (40)  NULL,
    [kc_curr_stat1]       VARCHAR (1)   NULL,
    [kc_curr_zip1]        VARCHAR (5)   NULL,
    [kc_curr_addr1]       VARCHAR (100) NULL,
    [kc_curr_addr1_nt]    VARCHAR (40)  NULL,
    [kc_curr_phone1]      VARCHAR (15)  NULL,
    [kc_curr_phone1_nt]   VARCHAR (40)  NULL,
    [kc_comp_stat1]       VARCHAR (1)   NULL,
    [kc_comp_zip1]        VARCHAR (5)   NULL,
    [kc_comp_addr1]       VARCHAR (100) NULL,
    [kc_comp_addr1_nt]    VARCHAR (40)  NULL,
    [kc_comp_phone1]      VARCHAR (20)  NULL,
    [kc_comp_phone1_nt]   VARCHAR (40)  NULL,
    [kc_comp_namea1]      VARCHAR (60)  NULL,
    [kc_job_title1]       VARCHAR (20)  NULL,
    [kc_id_no2]           VARCHAR (10)  NULL,
    [kc_birth_date2]      DATETIME      NULL,
    [kc_rela_code2]       VARCHAR (2)   NULL,
    [kc_cust_name2u]      NVARCHAR (60) NULL,
    [kc_papa_name2u]      NVARCHAR (60) NULL,
    [kc_mama_name2u]      NVARCHAR (60) NULL,
    [kc_mate_name2u]      NVARCHAR (60) NULL,
    [kc_legal_agent2]     NVARCHAR (60) NULL,
    [kc_cust_stat2]       VARCHAR (1)   NULL,
    [kc_house_stat2]      VARCHAR (1)   NULL,
    [kc_mobil_no2]        VARCHAR (12)  NULL,
    [kc_mobil_no2_nt]     VARCHAR (40)  NULL,
    [kc_perm_stat2]       VARCHAR (1)   NULL,
    [kc_perm_zip2]        VARCHAR (5)   NULL,
    [kc_perm_addr2]       VARCHAR (100) NULL,
    [kc_perm_addr2_nt]    VARCHAR (40)  NULL,
    [kc_perm_phone2]      VARCHAR (15)  NULL,
    [kc_perm_phone2_nt]   VARCHAR (40)  NULL,
    [kc_curr_stat2]       VARCHAR (1)   NULL,
    [kc_curr_zip2]        VARCHAR (5)   NULL,
    [kc_curr_addr2]       VARCHAR (100) NULL,
    [kc_curr_addr2_nt]    VARCHAR (40)  NULL,
    [kc_curr_phone2]      VARCHAR (15)  NULL,
    [kc_curr_phone2_nt]   VARCHAR (40)  NULL,
    [kc_comp_stat2]       VARCHAR (1)   NULL,
    [kc_comp_zip2]        VARCHAR (5)   NULL,
    [kc_comp_addr2]       VARCHAR (100) NULL,
    [kc_comp_addr2_nt]    VARCHAR (40)  NULL,
    [kc_comp_phone2]      VARCHAR (20)  NULL,
    [kc_comp_phone2_nt]   VARCHAR (40)  NULL,
    [kc_comp_namea2]      VARCHAR (60)  NULL,
    [kc_job_title2]       VARCHAR (20)  NULL,
    [kc_cust_name3u]      NVARCHAR (60) NULL,
    [kc_rela_code3]       VARCHAR (2)   NULL,
    [kc_mobil_no3]        VARCHAR (12)  NULL,
    [kc_curr_phone3]      VARCHAR (15)  NULL,
    [kc_comp_phone3]      VARCHAR (20)  NULL,
    [kc_cust_name4u]      NVARCHAR (60) NULL,
    [kc_rela_code4]       VARCHAR (2)   NULL,
    [kc_mobil_no4]        VARCHAR (12)  NULL,
    [kc_curr_phone4]      VARCHAR (15)  NULL,
    [kc_comp_phone4]      VARCHAR (20)  NULL,
    [kc_zip_code]         VARCHAR (5)   NULL,
    [kc_bill_addr]        VARCHAR (100) NULL,
    [kc_trans_addr]       VARCHAR (100) NULL,
    [kc_data_sign]        VARCHAR (10)  NULL,
    [kc_data_flag]        VARCHAR (10)  NULL,
    [kc_data_flag1]       VARCHAR (10)  NULL,
    [kc_data_flag2]       VARCHAR (10)  NULL,
    [kc_data_memo]        VARCHAR (150) NULL,
    [kc_ret_date]         DATETIME      NULL,
    [kc_boro_date]        DATETIME      NULL,
    [kc_boro_code]        VARCHAR (6)   NULL,
    [kc_boro_stat]        VARCHAR (1)   NULL,
    [kc_boro_memo]        VARCHAR (100) NULL,
    [kc_pusher_code]      VARCHAR (6)   NULL,
    [kc_pusher_date]      DATETIME      NULL,
    [kc_push_sort]        VARCHAR (4)   NULL,
    [kc_trace_date]       DATETIME      NULL,
    [kc_push_memo]        TEXT          NULL,
    [kc_push_memo2]       VARCHAR (200) NULL,
    [kc_push_memo3]       VARCHAR (300) NULL,
    [kc_loan_stat]        VARCHAR (1)   NULL,
    [kc_push_stat]        VARCHAR (1)   NULL,
    [kc_car_stat]         VARCHAR (1)   NULL,
    [kc_over_count]       TINYINT       NULL,
    [kc_pay_count]        TINYINT       NULL,
    [kc_dday_count]       SMALLINT      NULL,
    [kc_over_amt]         INT           NULL,
    [kc_break_amt]        INT           NULL,
    [kc_break_amt2]       INT           NULL,
    [kc_rema_amt]         INT           NULL,
    [kc_comp_code]        VARCHAR (4)   NULL,
    [kc_sales_code]       VARCHAR (6)   NOT NULL,
    [kc_loan_type]        VARCHAR (3)   NULL,
    [kc_car_brand]        VARCHAR (2)   NULL,
    [kc_car_model]        VARCHAR (30)  NULL,
    [kc_licn_no]          VARCHAR (10)  NULL,
    [kc_eng_no]           VARCHAR (20)  NULL,
    [kc_new_flag]         VARCHAR (1)   NULL,
    [kc_buy_date]         DATETIME      NULL,
    [kc_loan_perd]        TINYINT       NOT NULL,
    [kc_loan_fee]         INT           NULL,
    [kc_perd_fee]         INT           NOT NULL,
    [kc_total_price]      INT           NULL,
    [kc_brok_fee]         INT           NULL,
    [kc_brok_fee2]        INT           NULL,
    [kc_strt_date]        DATETIME      NOT NULL,
    [kc_strt_fee]         INT           NOT NULL,
    [kc_give_type]        VARCHAR (2)   NULL,
    [kc_give_amt]         INT           NULL,
    [kc_coll_amt]         INT           NULL,
    [kc_car_cc]           VARCHAR (5)   NULL,
    [kc_totm_fee]         INT           NULL,
    [kc_insu_flag]        VARCHAR (1)   NULL,
    [kc_rule_fee]         INT           NULL,
    [kc_issu_code]        VARCHAR (6)   NULL,
    [kc_aux_flag]         BIT           NULL,
    [kc_aux_amt]          TINYINT       NULL,
    [kc_pay_type]         VARCHAR (1)   NULL,
    [kc_dday_date]        DATETIME      NULL,
    [kc_licn_date]        DATETIME      NULL,
    [kc_pvall_amt]        INT           NULL,
    [kc_proc_amt]         INT           NULL,
    [kc_chk_no]           VARCHAR (12)  NULL,
    [kc_cap_code]         VARCHAR (2)   NOT NULL,
    [kc_intr_rate]        REAL          NULL,
    [kc_insu_sum]         INT           NULL,
    [kc_fitt1_amt]        SMALLINT      NULL,
    [kc_fitt2_amt]        SMALLINT      NULL,
    [kc_delay_code]       VARCHAR (4)   NULL,
    [kc_cred_chk]         BIT           NULL,
    [kc_cred_fee]         INT           NULL,
    [kc_cred_stat]        VARCHAR (1)   NULL,
    [kc_apply_stat]       VARCHAR (1)   NULL,
    [kc_comp_char2]       VARCHAR (2)   NULL,
    [kc_prod_type]        VARCHAR (4)   NULL,
    [kc_claims_amt]       INT           NULL,
    [kc_value_date]       DATETIME      NULL,
    [kc_oriclaims_amt]    INT           NULL,
    [kc_orivalue_date]    DATETIME      NULL,
    [kc_creditor_name]    VARCHAR (6)   NULL,
    [kc_rate_fee]         VARCHAR (2)   NULL,
    [kc_lawagents_code]   VARCHAR (2)   NULL,
    [kc_stock_date]       DATETIME      NULL,
    [kc_maturity_date]    DATETIME      NULL,
    [kc_idle_type]        VARCHAR (4)   NULL,
    [kc_idle_amt]         INT           NULL,
    [kc_idle_date]        DATETIME      NULL,
    [kc_bank_code]        VARCHAR (7)   NULL,
    [kc_acc_code]         VARCHAR (15)  NULL,
    [kc_crdt_user]        VARCHAR (10)  NULL,
    [kc_updt_user]        VARCHAR (10)  NULL,
    [kc_updt_date]        DATETIME      NULL,
    [PrintMark]           VARCHAR (1)   NULL,
    [CarrierType]         VARCHAR (6)   NULL,
    [CarrierId1]          VARCHAR (64)  NULL,
    [CarrierId2]          VARCHAR (64)  NULL,
    [NPOBAN]              VARCHAR (7)   NULL,
    [kc_insu_amt]         INT           NULL,
    [kc_insu_fee]         INT           NULL,
    [kc_insu_amt1]        INT           NULL,
    [kc_insu_fee1]        INT           NULL,
    [kc_insu_amt2]        INT           NULL,
    [kc_insu_fee2]        INT           NULL,
    [kc_insu_amt3]        INT           NULL,
    [kc_insu_fee3]        INT           NULL,
    [kc_mate_name]        VARCHAR (10)  NULL,
    [kc_papa_name]        VARCHAR (10)  NULL,
    [kc_mama_name]        VARCHAR (10)  NULL,
    [kc_cust_name1]       VARCHAR (10)  NULL,
    [kc_mate_name1]       VARCHAR (10)  NULL,
    [kc_papa_name1]       VARCHAR (10)  NULL,
    [kc_mama_name1]       VARCHAR (10)  NULL,
    [kc_cust_name2]       VARCHAR (10)  NULL,
    [kc_mate_name2]       VARCHAR (10)  NULL,
    [kc_papa_name2]       VARCHAR (10)  NULL,
    [kc_mama_name2]       VARCHAR (10)  NULL,
    [kc_cust_name3]       VARCHAR (10)  NULL,
    [kc_cust_name4]       VARCHAR (10)  NULL,
    [kc_comp_namex]       VARCHAR (60)  NULL,
    [kc_comp_namex1]      VARCHAR (60)  NULL,
    [kc_comp_namex2]      VARCHAR (60)  NULL,
    [kc_comp_name]        VARCHAR (20)  NULL,
    [kc_comp_name1]       VARCHAR (20)  NULL,
    [kc_comp_name2]       VARCHAR (20)  NULL,
    [kc_valid_month]      SMALLINT      NULL,
    [kc_valid_year]       SMALLINT      NULL,
    [kc_card_type]        VARCHAR (2)   NULL,
    [kc_card_no]          VARCHAR (20)  NULL,
    [kc_auth_code]        VARCHAR (10)  NULL,
    [kc_law_date]         DATETIME      NULL,
    [kc_comp_char]        VARCHAR (1)   NULL,
    [kc_link_no]          INT           NULL,
    [kc_accu_flag]        VARCHAR (1)   NULL,
    [kc_ret_code]         VARCHAR (6)   NULL,
    [kc_rewd_type]        VARCHAR (2)   NULL,
    [kc_issu_bank]        VARCHAR (4)   NULL,
    [kc_wire_bank]        VARCHAR (5)   NULL,
    [kc_wire_branch]      VARCHAR (30)  NULL,
    [kc_wire_acc]         VARCHAR (20)  NULL,
    [kc_remit_user]       NVARCHAR (60) NULL,
    [kc_remit_date]       DATETIME      NULL,
    [kc_insuend_date]     DATETIME      NULL,
    [kc_proc_fee]         INT           NULL,
    [kc_collarcar_fee]    INT           NULL,
    [kc_capremain_fee]    INT           NULL,
    [kc_curr_phone3_nt]   VARCHAR (40)  NULL,
    [kc_curr_phone4_nt]   VARCHAR (40)  NULL,
    [kc_mobil_no3_nt]     VARCHAR (40)  NULL,
    [kc_mobil_no4_nt]     VARCHAR (40)  NULL,
    [kc_partner_no]       VARCHAR (10)  NULL,
    [kc_agency_no]        VARCHAR (4)   NULL,
    [kc_partnerbank_no]   VARCHAR (3)   NULL,
    [kc_localagency_no]   VARCHAR (4)   NULL,
    [kc_partnerbill_date] DATETIME      NULL,
    [kc_otheragency_no]   VARCHAR (4)   NULL,
    [kc_regissu_type]     VARCHAR (1)   NULL,
    [kc_insuend_user]     VARCHAR (10)  NULL,
    [kc_push_memo4]       VARCHAR (150) NULL,
    [kc_bill_code]        VARCHAR (3)   NULL,
    [kc_line_no]          VARCHAR (20)  NULL,
    [kc_invo_flag]        VARCHAR (1)   NULL,
    [kc_buyback_user]     VARCHAR (10)  NULL,
    [kc_buyback_date]     SMALLDATETIME NULL,
    [kc_brand_code]       VARCHAR (2)   NULL,
    [kc_draft_addr]       VARCHAR (100) NULL,
    [kc_dect_amt]         INT           NULL,
    [kc_invo_caseno]      VARCHAR (10)  NULL,
    [kc_healthID_no]      VARCHAR (12)  NULL,
    [kc_healthID_no1]     VARCHAR (12)  NULL,
    [kc_healthID_no2]     VARCHAR (12)  NULL,
    [kc_rela_code6]       VARCHAR (2)   NULL,
    [kc_mobil_no6]        VARCHAR (12)  NULL,
    [kc_curr_phone6]      VARCHAR (15)  NULL,
    [kc_comp_phone6]      VARCHAR (20)  NULL,
    [kc_mobil_no6_nt]     VARCHAR (40)  NULL,
    [kc_curr_phone6_nt]   VARCHAR (40)  NULL,
    [kc_cust_name6u]      NVARCHAR (60) NULL,
    [kc_marketer_code]    VARCHAR (10)  NULL,
    [kc_marketing_type]   VARCHAR (2)   NULL,
    [kc_marketing_date]   DATETIME      NULL,
    [kc_householdID_no]   VARCHAR (20)  NULL,
    [kc_householdID_no1]  VARCHAR (20)  NULL,
    [kc_householdID_no2]  VARCHAR (20)  NULL,
    [kc_citizenship_type] VARCHAR (6)   NULL,
    [kc_batchprint_user]  VARCHAR (10)  NULL,
    [kc_batchprint_date]  SMALLDATETIME NULL,
    [kc_laborlist_stat]   VARCHAR (1)   NULL,
    [kc_laborlist_memo]   VARCHAR (100) NULL,
    [kc_laborlist_date]   SMALLDATETIME NULL,
    [kc_CCR_date]         SMALLDATETIME NULL,
    [kc_CCR_date1]        SMALLDATETIME NULL,
    [kc_CCR_date2]        SMALLDATETIME NULL,
    [CreatePerson]        VARCHAR (20)  NULL,
    [CreateDate]          DATETIME      NULL,
    [kc_member_no]        VARCHAR (20)  NULL,
    [kc_rece_fee]         INT           NULL,
    [kc_renewal_type]     VARCHAR (1)   NULL,
    [CompID]              VARCHAR (20)  NULL,
    [kc_bank_no]          VARCHAR (10)  NULL,
    [kc_bank_nont]        VARCHAR (10)  NULL,
    [kc_ATM_codeC]        VARCHAR (20)  NULL,
    [kc_ATM_codeB]        VARCHAR (20)  NULL
);

