CREATE TABLE [kcsd].[z_AmountUpTmp] (
    [id]                  INT            IDENTITY (1, 1) NOT NULL,
    [member_id]           INT            NULL,
    [member_no]           NVARCHAR (11)  NULL,
    [upgrade_loc_amount]  INT            NULL,
    [upgrade_bank_name]   NVARCHAR (50)  NULL,
    [upgrade_credit_no]   NVARCHAR (20)  NULL,
    [new_cp_no]           NVARCHAR (20)  NULL,
    [finish]              NVARCHAR (1)   NULL,
    [tmp_id_no]           NVARCHAR (10)  NULL,
    [tmp_name]            NVARCHAR (50)  NULL,
    [tmp_birthday]        NVARCHAR (10)  NULL,
    [tmp_issue_date]      NVARCHAR (10)  NULL,
    [tmp_issue_site]      NVARCHAR (10)  NULL,
    [tmp_issue_reason]    NVARCHAR (10)  NULL,
    [tmp_address]         NVARCHAR (250) NULL,
    [tmp_apply_date]      NVARCHAR (50)  NULL,
    [tmp_papa_nameu]      NCHAR (10)     NULL,
    [tmp_mama_nameu]      NCHAR (10)     NULL,
    [tmp_mate_nameu]      NCHAR (10)     NULL,
    [type_msg]            NVARCHAR (50)  NULL,
    [tmp_current_address] NVARCHAR (250) NULL,
    [tmp_tel]             NVARCHAR (50)  NULL,
    [tmp_link_name]       NVARCHAR (50)  NULL,
    [tmp_link_mobile]     NVARCHAR (20)  NULL,
    [tmp_link_relation]   NVARCHAR (4)   NULL,
    [tmp_work_type]       NVARCHAR (50)  NULL,
    [tmp_work_name]       NVARCHAR (50)  NULL,
    [tmp_work_tel]        NVARCHAR (50)  NULL,
    [tmp_create_type]     NVARCHAR (50)  NULL,
    [tmp_create_co]       NVARCHAR (50)  NULL,
    [tmp_bankCode]        NVARCHAR (50)  NULL,
    [tmp_bankName]        NVARCHAR (50)  NULL,
    [tmp_bankAcc]         NVARCHAR (50)  NULL,
    [tmp_line_id]         NVARCHAR (50)  NULL,
    CONSTRAINT [PK_z_AmountUpTmp] PRIMARY KEY CLUSTERED ([id] ASC)
);

