CREATE TABLE [kcsd].[z_Member] (
    [id]                      INT             IDENTITY (1, 1) NOT NULL,
    [name]                    NVARCHAR (50)   NULL,
    [mobile]                  NVARCHAR (50)   NULL,
    [mail]                    NVARCHAR (150)  NULL,
    [type]                    NVARCHAR (50)   NULL,
    [id_no]                   NVARCHAR (10)   NULL,
    [birthday]                NVARCHAR (10)   NULL,
    [address]                 NVARCHAR (250)  NULL,
    [curr_address]            NVARCHAR (250)  NULL,
    [curr_tel]                NVARCHAR (50)   NULL,
    [contact_person_name]     NVARCHAR (50)   NULL,
    [contact_person_tel]      NVARCHAR (50)   NULL,
    [contact_person_relation] NVARCHAR (50)   NULL,
    [company_name]            NVARCHAR (50)   NULL,
    [employment_state]        NVARCHAR (50)   NULL,
    [company_tel]             NVARCHAR (50)   NULL,
    [credit_state]            NVARCHAR (50)   NULL,
    [credit_bank]             NVARCHAR (50)   NULL,
    [refund_bank_no]          NVARCHAR (50)   NULL,
    [refund_bank_name]        NVARCHAR (50)   NULL,
    [refund_bank_acc]         NVARCHAR (50)   NULL,
    [line_id]                 NVARCHAR (50)   NULL,
    [credit_amount]           NVARCHAR (50)   NULL,
    [pw]                      NVARCHAR (250)  NULL,
    [checkId_error]           NVARCHAR (500)  NULL,
    [login_ok_msg]            NVARCHAR (50)   NULL,
    [apply_date]              NVARCHAR (50)   NULL,
    [issue_date]              NVARCHAR (10)   NULL,
    [issue_site]              NVARCHAR (10)   NULL,
    [issue_reason]            NVARCHAR (10)   NULL,
    [role]                    NVARCHAR (50)   NULL,
    [papa_nameu]              NVARCHAR (50)   NULL,
    [mama_nameu]              NVARCHAR (50)   NULL,
    [mate_nameu]              NVARCHAR (50)   NULL,
    [connection_time]         NVARCHAR (50)   NULL,
    [cp_no]                   NVARCHAR (10)   NULL,
    [browser]                 VARCHAR (1500)  NULL,
    [apply_date_dt]           DATETIME        NULL,
    [birthday_dt]             DATETIME        NULL,
    [last_login_time]         DATETIME        NULL,
    [login_day]               INT             NULL,
    [twca_msg]                NVARCHAR (1500) NULL,
    [twca_return_desc]        NVARCHAR (500)  NULL,
    [login_error_msg]         NVARCHAR (1500) NULL,
    [face_msg]                NVARCHAR (1500) NULL,
    [store_no]                NVARCHAR (50)   NULL,
    [kc_member_no]            NVARCHAR (11)   NULL,
    [kc_introduce_code]       NVARCHAR (11)   NULL,
    [longitude]               NVARCHAR (50)   NULL,
    [latitude]                NVARCHAR (50)   NULL,
    [kc_comp_code]            NVARCHAR (10)   NULL,
    [kc_sales_code]           NVARCHAR (10)   NULL,
    [ip]                      NVARCHAR (20)   NULL,
    [register_step]           INT             NULL,
    [dealer_role]             NVARCHAR (50)   NULL,
    [dealer_acc]              NVARCHAR (50)   NULL,
    [isStart]                 NVARCHAR (1)    NULL,
    [dealer_acc_name]         NVARCHAR (50)   NULL,
    [dealer_branch]           NVARCHAR (50)   NULL,
    [forget_pw_flag]          NVARCHAR (1)    NULL,
    [mark]                    NVARCHAR (50)   NULL,
    [dealer_firstLogin]       NVARCHAR (1)    NULL,
    [tmp_new_mobile]          NVARCHAR (50)   NULL,
    [update_time]             DATETIME        NULL,
    [voice_type]              NVARCHAR (1)    NULL,
    [voice_txt_mobile]        NVARCHAR (50)   NULL,
    [voice_txt_give]          NVARCHAR (50)   NULL,
    [register_cp_no]          NVARCHAR (10)   NULL,
    [area_code]               NVARCHAR (20)   NULL,
    [kc_updt_user]            VARCHAR (10)    NULL,
    [kc_updt_date]            SMALLDATETIME   NULL,
    [voice_txt_cq]            NVARCHAR (50)   NULL,
    [voice_txt_comp]          NVARCHAR (50)   NULL,
    [voice_txt_oaddress]      NVARCHAR (250)  NULL,
    [voice_subtype]           NVARCHAR (1)    NULL,
    [voice_subtype_2]         NVARCHAR (1)    NULL,
    [order_url]               NVARCHAR (1500) NULL,
    [order_type]              NVARCHAR (20)   NULL,
    [trade_type]              NVARCHAR (20)   NULL,
    [trade_info]              NVARCHAR (1000) NULL,
    [trade_url]               NVARCHAR (1500) NULL,
    CONSTRAINT [PK_z_Member] PRIMARY KEY CLUSTERED ([id] ASC)
);

